name: Build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    runs-on: ${{matrix.os}}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..
      - name: Build
        run: cmake --build . --config Release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.os}}-build
          path: |
            build/out/visa.*

