name: Build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    runs-on: ${{matrix.os}}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.os}}-build
          path: |
            ${{github.workspace}}/build/out/*
  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Get Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: artifacts/*
          generateReleaseNotes: true
          makeLatest: true


